### ISSUE TITLE
Uploaded thumbnail disappears when map is edited

### ISSUE THREAD

**Issue by wendy-guan** [cga-harvard/CAMP#12]
When a map is edited, for example when the user switched the base layer and saved the edit, the map's uploaded thumbnail will disappear. Please make the uploaded thumbnail not disappear when the map is edited.

**Comment by capooti** [comment]
hi @wendy-guan can you please give me further details? I cannot replicate this issue

**Comment by wendy-guan** [comment]
I just asked Prof. Xu to video record the experience. Will forward when I get it.

**Comment by wendy-guan** [comment]
This zip file contains the mp4 from Prof. Xu.
[20190907_004406.zip](https://github.com/cga-harvard/CAMP/files/3584864/20190907_004406.zip)

**Comment by capooti** [comment]
@wendy-guan I made a test with the same map: it didn't have an uploaded thumbnail at all. In such a case the behaviour is having the thumbnail updated at every map save (it is a GeoNode feature). If he wants to keep always the same thumbnail he should upload it as an image. Hope it is clear.

**Comment by wendy-guan** [comment]
Got it. Thanks!
