### ISSUE TITLE
CAMP staging not accepting uploads

### ISSUE THREAD

**Issue by blewis** [cga-harvard/CAMP#17]
Bug or geoserver down?

**Comment by capooti** [comment]
@bglewis I don't know what happened. GeoServer seems to have been reset (including default password) and seems not using the correct data directory

**Comment by capooti** [comment]
it looks like the main GeoServer process (which uses Tomcat) was stopped and GeoServer was started from the virtual environment usingn pavement. now it should be fixed

**Comment by wendy-guan** [comment]
Devika just restarted geoserver (after Sep. 13 power outage). Ben - could you please check and see if this issue can be closed? Thanks!
