### ISSUE TITLE
CAMP staging, GeoJSON file not uploading as regular user, only as admin

### ISSUE THREAD

**Issue by blewis** [cga-harvard/CAMP#18]
Here is professor Xu's language:

Many thanks the video you sent! I downloaded the geojson you used from 128 sever and try it on 128 sever, if I use admin user, it upload succeefully, if I used non admin user( common user) it failed. 
Then I try it on AMAP, The admin user and a common user, it succeeded, but another user named camp2018( I regestered for myself) which have same permisssion with admin user, it failed to upload(sever times,all failed). so, geojson's uploading is unstable.

**Comment by capooti** [comment]
@blewis I could successfully upload the geojson file you sent me by email using a not administrative account:
http://128.31.22.46/layers/geonode:tangxianzu_long_txt_2k_tst1

**Comment by blewis** [comment]
Problem solved.  It was Chinese chars in the Profile.  Will close this and open a new ticket.
