### ISSUE TITLE
Chinese characters in profile metadata and perhaps other fields causing problems

### ISSUE THREAD

**Issue by blewis** [cga-harvard/CAMP#20]
We need to make sure that all fields in all main user input parts of the system: People metadata, Group metadata, Group category metadata, Map metadata, Layer metadata, Document metadata, can support Chinese chars.  

We also have to be careful about encoding in these and anytime we store Chinese characters in CAMP.  For example I'm not sure how these metadata fields handle GBK versus UTF8.

**Comment by capooti** [comment]
This has been addressed.

**Comment by capooti** [comment]
hi @blewis I see you re-opened this ticket. Would you provide me a test case where you are experiencing this again?

**Comment by blewis** [comment]
Just leaving it open until it is tested and pushed to master so Zhejiang can install

**Comment by wendy-guan** [comment]
Has this been pushed to master? If yes we can close this ticket.

**Comment by capooti** [comment]
yes @wendy-guan just today but I'd like to test it. I am planning to do it on Tuesday

**Comment by capooti** [comment]
@wendy-guan @blewis this can be closed now.
