### ISSUE TITLE
ZJU server - admin user Identify hangs, regular user Identify limited to 10 IDs

### ISSUE THREAD

**Issue by wendy-guan** [cga-harvard/CAMP#22]
WANG Lijun needs some pointer on how to diagnose and resolve this issue.

**Comment by capooti** [comment]
hi @wendy-guan can you expand this? on which layer is happening?

**Comment by wendy-guan** [comment]
I will ask Prof. Xu to clarify and send video.

**Comment by wendy-guan** [comment]
Three videos showing scenarios from Prof. Xu:
1. admin account Idenfity existing layer: hangs
2. admin account Idenfity freshly uploaded layer: can't see feature IDs, but some attributes show up
3. regular user Identify: returns 10 features with ID and attributes, but there are many more features at that location.
[videos.zip](https://github.com/cga-harvard/CAMP/files/3653064/videos.zip)

**Comment by wendy-guan** [comment]
It is not practical to manually refresh permission settings for all existing layers - even if that could solve the problem.

**Comment by wendy-guan** [comment]
Prof. Xu just said that he found Identify problem on staging too, but limited to geojson layers. Admin user can't identify them (IDs not showing up). I don't have admin login to staging. Ben can you test that?

**Comment by capooti** [comment]
@wendy-guan this isn't a bug in my opinion. GeoExplorer relies on OpenLayers, and the ./app/static/externals/openlayers/lib/OpenLayers/Control/WMTSGetFeatureInfo.js assumes that when clicking on a point there should be more than 10 different features. If this is not acceptable by CAMP use cases, OpenLayers should be forked, specifically the above file should set the maxFeatures property to a value larger than 10.
I am not sure if it is possible to avoid the OpenLayers fork by overriding the maxFeatures property from geoexplorer source code (which is already forked).

**Comment by wendy-guan** [comment]
The maxFeatures limit explains "regular user Identify shows only 10 IDs", but how to explain "admin user Identify hangs, or shows some attributes but not IDs"? And that seems to happen on layers uploaded as geojson files? Or maybe that is only because his geojson files tend to have more overlapping features.

**Comment by capooti** [comment]
@wendy-guan I'd suggest to use this ticket to discuss about the 10 features limit and create a new ticket for the other issue (Identify hangs)

**Comment by wendy-guan** [comment]
Can you create an admin user for me on staging? Once I can replicate the "Identify hangs" issue as admin I will create a separate ticket here. Thanks!
Also, I have asked Prof. Xu to tell me how many overlapping features he had on the layer - if there are hundreds or thousands of features, would that explain why the tool hangs?

**Comment by wendy-guan** [comment]
Got the admin login from Ben and just tested on staging. For both regular user and admin user, Identify returned over a hundred IDs, no problem at all. Only if without login, public users have the 10 ID limit, which should be fine.
I also tested on ZJU server with regular user (I don't have admin login). Both public user and regular login returned only 10 IDs.

**Comment by capooti** [comment]
@wendy-guan yes that could be the reason of the problem. I checked and WFS Identify does NOT send a feature count parameter to GeoServer WFS, therefore GeoServer could hang the response if there are thousand of features. I believe that this will be fixed once they switch to WMS Identify (but with the 10 features limit, unless we change source code).
It looks like that they started experience these bugs again after we switched back to WFS Identify

**Comment by wendy-guan** [comment]
On staging, the Identify which returned over a hundred IDs did so very fast for me. Prof. Xu said he does not need all thousands of overlapping features to be returned, a hundred would be enough, but 10 is too few, that is for logged in users (regular and admin). For public users, 10 is fine. Let's wait for Ben to get me an admin login to the ZJU server, so I can test there, before we move on with this issue.

**Comment by capooti** [comment]
@wendy-guan I have seen only now your latest comment. Please keep in mind that currently on CAMP staging we use WMS Identify for anonymous users and WFS Identify for logged users. This decision (WMS identify for anonymous users) was done because in CAMP they don't want to provide downloads for many layers, and this way (using WFS for anonymous users) identify was not working as GeoNode disable WFS for layers which are not downloadable.

**Comment by wendy-guan** [comment]
There is no problem about this: "WMS Identify for anonymous users and WFS Identify for logged users." We just need to make it work on ZJU server the same way as it is working on staging.

**Comment by wendy-guan** [comment]
Just to report some additional testing results: Chrome and Edge behaved the same. I added some Chinese text in the tmpAdmin account profile, it didn't make any difference. Identify returned many IDs on ZJU server for tmpAdmin (worked the way we want it to); but regular account (my wguan login) showed only 10 IDs at the same location (Hangzhou), where we know there are over a hundred features. The wguan login behaved the same way as anonymous users on ZJU server.  On staging, any login account can return over a hundred IDs.

**Comment by capooti** [comment]
hi @wendy-guan as far as I remember if a user hasn't download permissions for a layer when identifying will get a WMS response which has the 10 feature limit (which is hard coded in OpenLayers, could be increased). Hope this clarify things

**Comment by wendy-guan** [comment]
Aha - this is a critical piece of info which I missed. So the WFS vs WMS Identify returns are not by which type of account the user login with, but by permission to particular layers. This makes perfect sense now. As far as I can see, both ZJU and CAMP staging are working as expected now. I just need to explain this to Prof. Xu. Thanks!

But, he also has the problem of Identify hangs forever, or returns partial info (attributes but not IDs). This is shown in his videos. Perhaps it is because there are too many overlapping points at one location, taking too long for the tool to bring up all the returns?

**Comment by capooti** [comment]
Yes, I believe that a WFS returning thousand of features could be what causes WM to hang. Could you upload the same layer where the identify hangs on the staging so that I can test and check logs?

**Comment by wendy-guan** [comment]
Identify does not hang on staging, only on ZJU server. The videos I included earlier show the two scenarios: for map #1678, it hung for Prof. Xu’s admin account, but not mine. For map #4451, it returned attributes but not ID for Prof. Xu’s admin account, but hung for my admin account.

**Comment by capooti** [comment]
@wendy-guan #1678 works correctly for me and I see the IDs on the identify left panel.
#4451 fails for me as well. Checking at the response from GeoServer I see an invalid WFS response:

```xml
<wfs:FeatureCollection xsi:schemaLocation="http://www.geonode.org/ http://amap.zju.edu.cn/geoserver/wfs?service=WFS&version=1.0.0&request=DescribeFeatureType&typeName=geonode%3Ahangzhoulingmu&access_token=0VKE5R6Tr3y7IEdxWTPLVQTVcKI2jR http://www.opengis.net/wfs http://amap.zju.edu.cn/geoserver/schemas/wfs/1.0.0/WFS-basic.xsd?access_token=0VKE5R6Tr3y7IEdxWTPLVQTVcKI2jR"><gml:boundedBy><gml:null>unknown</gml:null></gml:boundedBy></wfs:FeatureCollection>
```

I am not sure why GeoServer fails to return a valid WFS response. I would need to look in the GeoServer log file or have a layer which shows the same error in staging.

**Comment by wendy-guan** [comment]
Prof. Xu just said that after Wang Lijun update permissions, the hanging problem is gone. But the other problem remains on both ZJU server and staging: geojson uploaded layer when identify only shows attributes but not IDs. I confirmed this on staging. Here is an example: http://128.31.22.46/maps/2179/view.

**Comment by wendy-guan** [comment]
Correction: the hanging problem is only gone for some layers but not all. Here is one that is still unresponsive on ZJU server now: http://amap.zju.edu.cn/maps/4451/view.  I have asked Prof. Xu to upload this layer to staging so you can diagnose.

**Comment by capooti** [comment]
I will create a ticket with the problem of the IDs not showing up on the left side. I remember I already fixed it a few months ago I am not sure why now it is happening again.

Regarding the other problem, as discussed before, it is caused by GeoServer returning an unknown geometry on the WFS GetFeature response. There are similar issues reporting this to the GeoServer list (like this one: https://osgeo-org.atlassian.net/browse/GEOS-1165), I have no idea how this can be fixed. Is there a way to get the GeoServer log of the error? (the best would be to find this error on our staging too)

**Comment by wendy-guan** [comment]
I think the two problems are from the same bug. The same layer (uploaded from geojson) are on both ZJU and staging now. Using my admin logins on both servers, they behave basically the same: left side IDs are always missing. But on ZJU server sometimes it does not return anything, sometimes (click again and again) it will return the popup with right side showing attributes. It is "hit and miss", but not because of my click missed the center of the point, since I zoomed in to make sure the click is on point. On Staging, clicks don't miss. 
http://128.31.22.46/maps/2183/view
http://amap.zju.edu.cn/maps/4451/view

**Comment by capooti** [comment]
@wendy-guan did you read this?
https://github.com/cga-harvard/CAMP/issues/24

**Comment by wendy-guan** [comment]
Thanks - just read it!  This explains the left table missing problem (I will explain to them), but does not explain the "hit and miss" sometimes not returning anything problem (which only happens on ZJU server).  Did you experience that yourself?

**Comment by capooti** [comment]
yes. As I wrote is a GeoServer failure to return the geometry for some reason.
I can check on the GeoServer list but I am not too much optimistic there is an easy solution for this.
Maybe it is worth to try to delete and update the layer again.

**Comment by wendy-guan** [comment]
1. For geojson uploaded layers, Identify shows attributes on the right, but not IDs on the left. This is on both ZJU and Staging. Example: http://128.31.22.46/maps/2179/view.
> 
> Solution: This is not a bug. The problem is because that the ID used for the left panel is the first field. In geojson files the default first field is geometry, and that is why there is no information. If you changed the order of the attribute fields and use ID as the first field for Identify, it will show up as supposed to.

徐按： 按所示方法操作，可以了。
Prof. Xu confirmed that this indeed works.

> > 2. For some layers, Identify does not return anything. This is found on ZJU server, but not seen on Staging yet. Example: http://amap.zju.edu.cn/maps/4451/view.
> 
> No solution: The same layer when uploaded on staging does not have this problem. http://128.31.22.46/maps/2183/view. Try remove the problematic layer from ZJU server and re-upload. 

徐按：这个情况我们这边没出现，我可以打开。
Prof. Xu said this problem is not appearing on ZJU server for him since Wang Lijun synchronized the permissions a couple of days ago. 

We may consider this resolved.  I will close this ticket now.
