### ISSUE TITLE
Download of geojson in geojson format does not work

### ISSUE THREAD

**Issue by blewis** [cga-harvard/CAMP#5]
Here is an example layer.  It is in UTF8 and has contains long text.  Longest piece is about 2400 Chinese chars. 
Download for geojson did not work but all other formats seem to work.  Then downloading geojson text flashes then shows a json reader in the browser (firefox).  Might be a mimetype issue.  Downloading the original datasets which was geojson works, perhaps because the file is delivered zip compressed.

**Comment by capooti** [comment]
@blewis I can't see the file

**Comment by capooti** [comment]
I used your file in the email. For me it correctly uploaded and can be downloaded:
http://128.31.22.46/geoserver/ows?srsName=EPSG%3A4326&outputFormat=json&service=WFS&srs=EPSG%3A4326&request=GetFeature&typename=geonode%3Atangxianzu_long_txt_2k1&version=1.0.0&access_token=IlAMl3DTEjTyRNL5p1mg1ggNYyc6E9

can you specify which error you noticed? thanks

**Comment by blewis** [comment]
Sorry, it looks like it is a formatting issue in the browser.  With firefox I see a flash of content then this view 
![image](https://user-images.githubusercontent.com/812849/64287310-518a3200-cf2d-11e9-8db2-955c9808d29d.png)
IE and Chrome display the full text in the browser.  It is a browser default display setting for json.  So no download problem.  Thanks.
