### ISSUE TITLE
Field order in Identify reponse not working because WFS disabled

### ISSUE THREAD

**Issue by blewis** [cga-harvard/CAMP#8]
Now can WFS be safely re-enabled?

**Comment by wendy-guan** [comment]
What is the Identify tool currently use - WFS or WMS?  Is this related to #16 - Identify only shows 10 attributes?

**Comment by capooti** [comment]
I still didn't move back GeoExplorer to use WFS. I am planning to do this tomorrow. In any case note that WMS is used by unlogged users, so they would experience this problem (fields order) and the other one reported (10 fields).

**Comment by wendy-guan** [comment]
I just closed #16.

**Comment by capooti** [comment]
I have re-enabled WFS Identify.
