### ISSUE TITLE
Zhejiang team -- establish a development and testing environment.

### ISSUE THREAD

**Issue by blewis** [cga-harvard/CAMP#9]
This is everyone's responsibility to communicate between teams.

Testing at this point should only be done on CGA CAMP Staging server.  No testing should be done on CAMP Production and no improvements should be brought piecemeal into Production.

Once CGA CAMP Staging is completely bug free and has been tested by Zhejiang team and approved, next step is to reinstall CAMP on Zhejiang development server.  

Once the new version has been installed and fully tested, then the new version can be installed on CAMP production server.

From that point forward the Zhejiang Dev server and Prod servers should be the same.  A new fix should be first tested on Dev before moving to Prod.

**Comment by wendy-guan** [comment]
From: Guan, Wendy 
Sent: Thursday, September 05, 2019 11:09 AM
To: yongmingxu1967@zju.edu.cn
Cc: 王立君 (3140102640@zju.edu.cn) <3140102640@zju.edu.cn>; 张丰老师 <zfcarnation@zju.edu.cn>
Subject: RE: Another urgent bug report from AMAP

(Translated)
Dear Prof. Xu,

Paolo has recently changed a lot of code when solving various problems. The correct upgrade procedure is:
1. Paolo will update the new code to http://128.31.22.46/ as they become available, and inform you of the test. Give us your feedback when you find any problem. This continues until you confirm that all important issues are resolved.
2. Wang Lijun installs the same system as http://128.31.22.46/ on his own computer,  make ensure that the versions of the various components are the same. Then make changes only on the places where Zhejiang University requires. You test it on his computer and give your feedback to him. If he can't solve it he may consult Paolo. This continues until you confirm that all important issues are resolved.
3. Wang Lijun installs the system tested on his own computer to the Zhejiang University server http://amap.zju.edu.cn/. This is the real system for the end users.

The versions of the various components on the Zhejiang University server now are different from those used by Paolo. His new code has no problem at http://128.31.22.46/, but when it is directly applied to http://amap.zju.edu.cn/, problems arise. The most straightforward way to deal with this is to let Wang Lijun roll http://amap.zju.edu.cn/ back to the old and more stable version. Wait for the above steps 1-2 to complete and then go to step 3.

Hurrying too much could delay the arrival. Please concentrate on testing http://128.31.22.46/ and report problems to us (record with video and attach the problem file). Thank you for your cooperation!

Wendy

(Original)
徐老师：你好！

最近Paolo在解决各种问题时更改了不少代码。正确的升级程序是：
1.	Paolo随时把新代码更新到http://128.31.22.46/ 上，通知你测试。发现问题就反馈给我们，直到你确认所有的重要问题都解决了。
2.	王立君在他自己的电脑上安装和http://128.31.22.46/完全一样的系统，保证各个部件的版本都要相同。然后改动只有浙大需要改动的地方。你再在他的电脑上测试，发现问题就反馈给他。他解决不了的可以问Paolo，直到你确认所有的重要问题都解决了。
3.	王立君把在他自己的电脑上测试好的系统再全盘安装到浙大服务器http://amap.zju.edu.cn/ 上。这才是面对用户的真正系统。

现在浙大服务器上的各个部件的版本都和Paolo更改代码时用的版本不一样。新代码在http://128.31.22.46/ 上我们测试没有问题，直接贴补到http://amap.zju.edu.cn/ 上，出问题了。最直接的处理办法是让王立君把http://amap.zju.edu.cn/ 退回到原来比较稳定的旧版。等上面1-2步骤完成了再走第3步。

欲速则不达。请你集中精力测试http://128.31.22.46/，发现问题就反馈给我们（用视频记录并附上出问题的文件）。谢谢配合！

关

**Comment by capooti** [comment]
@wendy-guan maybe you could remove emails from your comment. This is a public page, so emails could be harvested by spammer bots

**Comment by wendy-guan** [comment]
Thanks!  removed.
